# Generated by Django 5.1.2 on 2024-10-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licao',
            options={'verbose_name': 'Lição', 'verbose_name_plural': 'Lições'},
        ),
    ]
