# Generated by Django 5.1.2 on 2024-10-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licao', '0002_alter_licao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='conteudo_html',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='licao',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
