# Generated by Django 5.1.2 on 2024-10-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licao', '0003_alter_licao_conteudo_html_alter_licao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='conteudo_html',
            field=models.TextField(),
        ),
    ]
