# Generated by Django 5.1.2 on 2024-10-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licao', '0004_alter_licao_conteudo_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
